services:
   accounts:
      image: "mohdtausif25/accounts:a1"
      container_name: accounts_ms
      ports:
         - "8080:8080"
      deploy:
         resources:
            limits:
               memory: 500m
      networks:
         - easybank
   loans:
      image: "mohdtausif25/loans:l1"
      container_name: loans_ms
      ports:
         - "9090:9090"
      deploy:
         resources:
            limits:
               memory: 500m
      networks:
         - easybank
   cards:
      image: "mohdtausif25/cards:c1"
      container_name: cards_ms
      ports:
         - "9000:9000"
      deploy:
         resources:
            limits:
               memory: 500m
      networks:
         - easybank
networks:
   easybank:
      driver: "bridge"