spring:
   application:
      name: "configserver"
   profiles:
      active: native
   cloud:
      config:
         server:
            native:
               search-locations: "classpath:/config"
               

logging:
   level:
      org:
         springframework: info
         
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8071